#############################################################################
# Makefile for building: Pacman_Game
# Generated by qmake (3.1) (Qt 5.11.1)
# Project:  Pacman_Game.pro
# Template: app
# Command: /Users/cocoastarrion/Qt/5.11.1/clang_64/bin/qmake -o Makefile Pacman_Game.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include -I../../../../Qt/5.11.1/clang_64/mkspecs/macx-clang
QMAKE         = /Users/cocoastarrion/Qt/5.11.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/cocoastarrion/Qt/5.11.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/cocoastarrion/Qt/5.11.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Pacman_Game1.0.0
DISTDIR = /Users/cocoastarrion/Documents/CSPROJECTS/C++/Pacman_Game/.tmp/Pacman_Game1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wl,-rpath,@executable_path/Frameworks
LIBS          = $(SUBLIBS) -L/usr/local/lib -lsfml-audio -lsfml-graphics -lsfml-system -lsfml-network -lsfml-window 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = ../../../../Qt/5.11.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/spec_post.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/toolchain.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/mac.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/lex.prf \
		Pacman_Game.pro Game.h \
		Creature.h \
		Graph_Control.h \
		Creature_Graphic_Info.h \
		A_star.h \
		Portal.h \
		Search_Node.h main.cpp
QMAKE_TARGET  = Pacman_Game
DESTDIR       = 
TARGET        = Pacman_Game

####### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Pacman_Game.pro ../../../../Qt/5.11.1/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt/5.11.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/spec_post.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/toolchain.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/mac.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.11.1/clang_64/mkspecs/features/lex.prf \
		Pacman_Game.pro
	$(QMAKE) -o Makefile Pacman_Game.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../../../Qt/5.11.1/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.11.1/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.11.1/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.11.1/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt/5.11.1/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.11.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.11.1/clang_64/mkspecs/common/clang.conf:
../../../../Qt/5.11.1/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/5.11.1/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/spec_post.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/toolchain.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/toolchain.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/default_pre.prf:
deployment.pri:
../../../../Qt/5.11.1/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/qml_debug.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/mac.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/qmake_use.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/file_copies.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.11.1/clang_64/mkspecs/features/lex.prf:
Pacman_Game.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Pacman_Game.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp Graph_Control.h \
		/usr/local/include/SFML/Graphics.hpp \
		/usr/local/include/SFML/Window.hpp \
		/usr/local/include/SFML/System.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/System/Clock.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/System/Err.hpp \
		/usr/local/include/SFML/System/FileInputStream.hpp \
		/usr/local/include/SFML/System/InputStream.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/System/Lock.hpp \
		/usr/local/include/SFML/System/MemoryInputStream.hpp \
		/usr/local/include/SFML/System/Mutex.hpp \
		/usr/local/include/SFML/System/Sleep.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/String.inl \
		/usr/local/include/SFML/System/Thread.hpp \
		/usr/local/include/SFML/System/Thread.inl \
		/usr/local/include/SFML/System/ThreadLocal.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.inl \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/System/Vector3.hpp \
		/usr/local/include/SFML/System/Vector3.inl \
		/usr/local/include/SFML/Window/Context.hpp \
		/usr/local/include/SFML/Window/Export.hpp \
		/usr/local/include/SFML/Window/GlResource.hpp \
		/usr/local/include/SFML/Window/ContextSettings.hpp \
		/usr/local/include/SFML/Window/Event.hpp \
		/usr/local/include/SFML/Window/Joystick.hpp \
		/usr/local/include/SFML/Window/Keyboard.hpp \
		/usr/local/include/SFML/Window/Mouse.hpp \
		/usr/local/include/SFML/Window/Sensor.hpp \
		/usr/local/include/SFML/Window/Touch.hpp \
		/usr/local/include/SFML/Window/VideoMode.hpp \
		/usr/local/include/SFML/Window/Window.hpp \
		/usr/local/include/SFML/Window/WindowHandle.hpp \
		/usr/local/include/SFML/Window/WindowStyle.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/CircleShape.hpp \
		/usr/local/include/SFML/Graphics/Shape.hpp \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/VertexArray.hpp \
		/usr/local/include/SFML/Graphics/Vertex.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		/usr/local/include/SFML/Graphics/PrimitiveType.hpp \
		/usr/local/include/SFML/Graphics/ConvexShape.hpp \
		/usr/local/include/SFML/Graphics/Font.hpp \
		/usr/local/include/SFML/Graphics/Glyph.hpp \
		/usr/local/include/SFML/Graphics/Texture.hpp \
		/usr/local/include/SFML/Graphics/Image.hpp \
		/usr/local/include/SFML/Graphics/RectangleShape.hpp \
		/usr/local/include/SFML/Graphics/RenderTarget.hpp \
		/usr/local/include/SFML/Graphics/View.hpp \
		/usr/local/include/SFML/Graphics/RenderTexture.hpp \
		/usr/local/include/SFML/Graphics/RenderWindow.hpp \
		/usr/local/include/SFML/Graphics/Shader.hpp \
		/usr/local/include/SFML/Graphics/Glsl.hpp \
		/usr/local/include/SFML/Graphics/Glsl.inl \
		/usr/local/include/SFML/Graphics/Sprite.hpp \
		/usr/local/include/SFML/Graphics/Text.hpp \
		Game.h \
		Creature.h \
		Portal.h \
		A_star.h \
		Search_Node.h \
		Creature_Graphic_Info.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Pacman_Game/bin || mkdir -p $(INSTALL_ROOT)/opt/Pacman_Game/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Pacman_Game/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Pacman_Game/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Pacman_Game/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

